### ISSUE TITLE
Exception, NoClassFound TemporaryPlayer

### ISSUE THREAD

**Issue by almandoro** [Elikill58/Negativity#138]
**Describe the bug**
Plugin probaby can't talk to ProtocolLib. When player joins it produces massive exceptions due to the didn't find class TemporaryPlayer

**Your plugin version**
newest

**Your platform version (and precise the platforme (spigot/sponge))**
1.8.8 Spigot

**Screenshots**

**Error / Logs**
If applicable, add logs of error (copy/paste on pastebin/hastebin).
https://pastebin.com/yu7A71HA

**Additional context**

**Comment by almandoro** [comment]
[18:18:44] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Negativity v1.8
org.bukkit.event.EventException

**Comment by almandoro** [comment]
[18:18:44] [Server thread/WARN]: Could not pass incoming plugin message to Negativity v1.8
java.lang.NullPointerException

**Comment by almandoro** [comment]
[18:18:44] [Server thread/WARN]: [Negativity] Task #98 for Negativity v1.8 generated an exception
java.lang.NullPointerException
	at com.elikill58.negativity.universal.Version.getVersionByName(Version.java:61) ~[?:?]
	at com.elikill58.negativity.spigot.support.ProtocolSupportSupport.getPlayerVersion(ProtocolSupportSupport.java:12) ~[?:?]
	at com.elikill58.negativity.spigot.SpigotNegativityPlayer.<init>(SpigotNegativityPlayer.java:96) ~[?:?]
	at com.elikill58.negativity.spigot.SpigotNegativityPlayer.lambda$1(SpigotNegativityPlayer.java:749) ~[?:?]

**Comment by almandoro** [comment]
[18:18:44] [Netty Epoll Server IO #1/ERROR]: [Negativity] Unhandled exception occured in onPacketReceiving(PacketEvent) for Negativity
java.lang.NoClassDefFoundError: com/comphenix/protocol/injector/server/TemporaryPlayer

**Comment by almandoro** [comment]
Then it keeps spawning new Threads in infinite loop, which cannot be handled
[18:19:24] [Craft Scheduler Thread - 173/WARN]: Exception in thread "Craft Scheduler Thread - 173" 
[18:19:24] [Craft Scheduler Thread - 173/WARN]: org.apache.commons.lang.UnhandledException: Plugin Negativity v1.8 generated an exception while executing task 97

**Comment by Elikill58** [comment]
Hello,

1) Please, don't spam. Make 1 message with all informations
2) For the main problem, it's because you have an old version of ProtocolLib. Please update it and it will be fine :)
3) For the "[18:18:44] [Server thread/WARN]: [Negativity] Task #98 for Negativity v1.8 generated an exception
java.lang.NullPointerException
at com.elikill58.negativity.universal.Version.getVersionByName(Version.java:61) ~[?:?]" I know this problem, it appear with ProtocolSupport with 1.15.2's player, apparently.

I will fix the second.

**Comment by Elikill58** [comment]
ProtocolSupport fixed in https://github.com/Elikill58/Negativity/commit/56dbb1e0d0153456a8e8eac16aadbe83336fb6a6
