### ISSUE TITLE
NoSuchMethodException when using Negativity together with BentoBox

### ISSUE THREAD

**Issue by Flying--Dutchman** [Elikill58/Negativity#292]
**Describe the bug**
When using BentoBox (OneSkyBlock), after breaking the special block I get a "NoSuchMethodExceeption" in my log. 

**Your plugin version**
1.11.1

**Your server version (and the software type (spigot/sponge))**
PaperMC 1.18.1 (build 145)

**Error / Logs**
If applicable, add logs of error (copy/paste on pastebin/hastebin).

```
[23:50:19 WARN]: java.lang.NoSuchMethodException: net.minecraft.core.BaseBlockPosition.getX(),
[23:50:19 WARN]: 	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675),
[23:50:19 WARN]: 	at Negativity.jar//com.elikill58.negativity.spigot.protocols.NukerProtocol.onPacketDig(NukerProtocol.java:73),
[23:50:19 WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor270.execute(Unknown Source),
[23:50:19 WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69),
[23:50:19 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80),
[23:50:19 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70),
[23:50:19 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628),
[23:50:19 WARN]: 	at Negativity.jar//com.elikill58.negativity.spigot.packets.PacketManager.lambda$0(PacketManager.java:35),
[23:50:19 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101),
[23:50:19 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483),
[23:50:19 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1547),
[23:50:19 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480),
[23:50:19 WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470),
[23:50:19 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264),
[23:50:19 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317),
[23:50:19 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Elikill58** [comment]
Only with this type of block ? Not with all ?

**Comment by Flying--Dutchman** [comment]
Ah my bad, apparently also on other blocks. Therefore I can't say if its BentoBox related. Looking at the stacktrace, it doesn't seem like it.

Note to myself; Don't open issues in the middle of the night.

**Comment by Elikill58** [comment]
xD No problem, open issue when you want.

The issue should be fixed in this commit: https://github.com/Elikill58/Negativity/commit/e29f0448f0263eaf57872f5f63786ae988d7a5f4 . I just make "ghost update" like that:
![image](https://user-images.githubusercontent.com/17381066/148928608-642e9c43-b0a0-4457-b690-0ee09bcd8b05.png)

The new build is fine !

**Comment by Flying--Dutchman** [comment]
Works perfectly, thank you very much :+1:
