### ISSUE TITLE
scheduler for stats crash

### ISSUE THREAD

**Issue by InterVi** [Elikill58/Negativity#3]
Get server bound address before starting network. This need move to post initialization event or next.

`[11:09:50 ERROR] [Sponge]: The Scheduler tried to run the task negativity-A-3 owned by Plugin{id=negativity, name=Negativity, version=1.1.1, description=It's an Advanced AntiCheat Detection, authors=[Elikill58, RedNesto], source=mods/Negativity.jar}, but an error occured.
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_192]
        at com.elikill58.negativity.sponge.SpongeNegativity$1.run(SpongeNegativity.java:134) ~[SpongeNegativity$1.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-7.1.5-RC139]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-7.1.5-RC139]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_192]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_192]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]`

...

`[11:09:51 INFO]: Starting Minecraft server on *:25565`

**Comment by Elikill58** [comment]
Hello, thanks for report :) i will fix it !
