### ISSUE TITLE
[Bug] Error when alerting

### ISSUE THREAD

**Issue by EpicPlayerA10** [Elikill58/Negativity#313]
### Which platform are you using ?

Paper

### Versions of Negativity and of the server

My version is: spigot: v1_18_R2. Negativity 1.12

### Step to reproduce

Uhh.. It is completly random. Mostly when players are pvp'ing

### Errors / Logs

```
[19:22:32 WARN]: java.lang.IllegalStateException: PlayerCheatEvent may only be triggered synchronously.
[19:22:32 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:657)
[19:22:32 WARN]: 	at Negativity(2).jar//com.elikill58.negativity.spigot.SpigotNegativity.alertMod(SpigotNegativity.java:514)
[19:22:32 WARN]: 	at Negativity(2).jar//com.elikill58.negativity.spigot.SpigotNegativity.alertMod(SpigotNegativity.java:463)
[19:22:32 WARN]: 	at Negativity(2).jar//com.elikill58.negativity.spigot.protocols.ForceFieldProtocol.lambda$2(ForceFieldProtocol.java:78)
[19:22:32 WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[19:22:32 WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[19:22:32 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:22:32 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:22:32 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:22:32 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by EpicPlayerA10** [comment]
Thanks for fast response and fix :)

**Comment by Elikill58** [comment]
> Thanks for fast response and fix :)

With pleasure :) You can come on discord for all dev build !
