### ISSUE TITLE
[Bug] Error caused by accessing google.fr while the plugin is enabled

### ISSUE THREAD

**Issue by BingYanchi** [Elikill58/Negativity#323]
### Which platform are you using ?

Spigot

### Versions of Negativity and of the server

My version is: 2.4.2

### Step to reproduce

1. run server
2. a error on console

I don't know why this problem occurs every time, but at least China can't access Google, and I don't know why I want to access google.fr

### Errors / Logs

[01:35:18 INFO]: [Negativity] An error occured while trying to make web request to: https://google.fr
[01:35:18 WARN]: java.net.SocketTimeoutException: connect timed out
[01:35:18 WARN]:        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
[01:35:18 WARN]:        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
[01:35:18 WARN]:        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
[01:35:18 WARN]:        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
[01:35:18 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[01:35:18 WARN]:        at java.base/java.net.Socket.connect(Socket.java:608)
[01:35:18 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:297)
[01:35:18 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
[01:35:18 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
[01:35:18 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
[01:35:18 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
[01:35:18 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
[01:35:18 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
[01:35:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
[01:35:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
[01:35:18 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
[01:35:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
[01:35:18 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[01:35:18 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[01:35:18 WARN]:        at com.elikill58.negativity.universal.utils.UniversalUtils.getContentFromURL(UniversalUtils.java:205)
[01:35:18 WARN]:        at com.elikill58.negativity.universal.utils.UniversalUtils.getContentFromURL(UniversalUtils.java:184)
[01:35:18 WARN]:        at com.elikill58.negativity.universal.utils.UniversalUtils.lambda$init$3(UniversalUtils.java:337)
[01:35:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Elikill58** [comment]
Trying to access to google is mostly to check if you have internet connection. Sorry for the issue, I will fix it
