### ISSUE TITLE
[Bug] Bungee Plugin Channel Error

### ISSUE THREAD

**Issue by BingYanchi** [Elikill58/Negativity#324]
### Which platform are you using ?

Bungeecord

### Versions of Negativity and of the server

My version is: 2.4.2

### Step to reproduce

When a cheater appears on the Spigot server, the Bungee side cannot prompt alerts and warnings, and prompts an error

### Errors / Logs

[01:35:18 ERROR]: java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.api.connection.Server.getInfo()" because the return value of "net.md_5.bungee.api.connection.ProxiedPlayer.getServer()" is null
[01:35:18 ERROR]:       at com.elikill58.negativity.bungee.impl.entity.BungeePlayer.getServerName(BungeePlayer.java:101)
[01:35:18 ERROR]:       at com.elikill58.negativity.common.ProxyEventsManager.onChannelMessage(ProxyEventsManager.java:97)
[01:35:18 ERROR]:       at com.elikill58.negativity.api.events.EventManager$HandleBasedListener.call(EventManager.java:211)
[01:35:18 ERROR]:       at com.elikill58.negativity.api.events.EventManager.lambda$callEvent$1(EventManager.java:166)
[01:35:18 ERROR]:       at java.base/java.util.HashMap.forEach(HashMap.java:1421)
[01:35:18 ERROR]:       at com.elikill58.negativity.api.events.EventManager.callEvent(EventManager.java:163)
[01:35:18 ERROR]:       at com.elikill58.negativity.api.events.EventManager.callEvent(EventManager.java:157)
[01:35:18 ERROR]:       at com.elikill58.negativity.bungee.BungeeListeners.onNegativityPluginMessageReceived(BungeeListeners.java:75)
[01:35:18 ERROR]:       at jdk.internal.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
[01:35:18 ERROR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:35:18 ERROR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01:35:18 ERROR]:       at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
[01:35:18 ERROR]:       at net.md_5.bungee.event.EventBus.post(EventBus.java:50)
[01:35:18 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466)
[01:35:18 ERROR]:       at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:288)
[01:35:18 ERROR]:       at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:93)
[01:35:18 ERROR]:       at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114)
[01:35:18 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[01:35:18 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[01:35:18 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[01:35:18 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[01:35:18 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[01:35:18 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[01:35:18 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[01:35:18 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[01:35:18 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[01:35:18 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[01:35:18 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[01:35:18 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[01:35:18 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[01:35:18 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[01:35:18 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[01:35:18 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[01:35:18 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[01:35:18 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[01:35:18 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[01:35:18 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[01:35:18 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[01:35:18 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[01:35:18 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[01:35:18 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[01:35:18 ERROR]:       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[01:35:18 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
[01:35:18 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
[01:35:18 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[01:35:18 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[01:35:18 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Elikill58** [comment]
Can you tell me your plugin list ?
