### ISSUE TITLE
[Bug] Proxy error when player login: SocketTimeoutException: Connect timed out: https://api.spigotmc.org/legacy/update.php?resource=86874

### ISSUE THREAD

**Issue by Lionel-1998** [Elikill58/Negativity#344]
### Which platform are you using ?

Paper, Bungeecord

### Versions of Negativity and of the server

My version is: Bungeecord 1.19 , Paper 1.19.2 , Negativity V2 2.5.1

### Step to reproduce

When a player join my server , Error appear on both of my Bungeecord server and Paper server , I don't know why. And I don't know how to config ban and warn file in bungeecord config. I set processor: proxy on both of my Paper server , and I have a MySQL database , I don't know what kind of processor i should choose on Bungeecord config. Please help me~

### Errors / Logs

==============Log on Bungeecord=================
19:42:55 [信息] Loaded plugin cmd_find version git:cmd_find:1.19-R0.1-SNAPSHOT:02548c4:1663 by SpigotMC
19:42:55 [信息] Loaded plugin BungeeNegativity version 2.5.1 by Elikill58
19:45:07 [信息] [Lionel90s] <-> ServerConnector [login] has connected
19:45:11 [信息] [ServerTest] <-> ServerConnector [login] has connected
19:45:12 [信息] [BungeeNegativity] An error occured while trying to make web request to: https://api.spigotmc.org/legacy/update.php?resource=86874
19:45:12 [严重] java.net.SocketTimeoutException: Connect timed out

19:45:12 [严重]     at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)

19:45:12 [严重]     at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)

19:45:12 [严重]     at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)

19:45:12 [严重]     at java.base/java.net.Socket.connect(Socket.java:633)

19:45:12 [严重]     at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)

19:45:12 [严重]     at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)

19:45:12 [严重]     at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)

19:45:12 [严重]     at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)

19:45:12 [严重]     at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)

19:45:12 [严重]     at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)

19:45:12 [严重]     at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)

19:45:12 [严重]     at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)

19:45:12 [严重]     at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)

19:45:12 [严重]     at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)

19:45:12 [严重]     at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)

19:45:12 [严重]     at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)

19:45:12 [严重]     at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)

19:45:12 [严重]     at com.elikill58.negativity.universal.utils.UniversalUtils.getContentFromURLWithException(UniversalUtils.java:240)

19:45:12 [严重]     at com.elikill58.negativity.universal.utils.UniversalUtils.getContentFromURL(UniversalUtils.java:204)

19:45:12 [严重]     at com.elikill58.negativity.universal.utils.UniversalUtils.getContentFromURL(UniversalUtils.java:192)

19:45:12 [严重]     at com.elikill58.negativity.universal.utils.UniversalUtils.getLatestVersionString(UniversalUtils.java:328)

19:45:12 [严重]     at com.elikill58.negativity.universal.utils.UniversalUtils.getLatestVersion(UniversalUtils.java:332)

19:45:12 [严重]     at com.elikill58.negativity.universal.utils.UniversalUtils.getLatestVersionIfNewer(UniversalUtils.java:341)

19:45:12 [严重]     at com.elikill58.negativity.common.ConnectionManager.lambda$onConnect$3(ConnectionManager.java:88)

19:45:12 [严重]     at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)

19:45:12 [严重]     at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)

19:45:12 [严重]     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)

19:45:12 [严重]     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)

19:45:12 [严重]     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)

19:45:12 [严重]     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)

19:45:12 [严重]     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

19:45:16 [信息] [BungeeNegativity] An error occured while trying to make web request to: https://api.spigotmc.org/legacy/update.php?resource=86874
19:45:27 [严重] java.net.SocketTimeoutException: Connect timed out

19:45:27 [严重]     at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)

19:45:27 [严重]     at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)

19:45:27 [严重]     at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)

19:45:27 [严重]     at java.base/java.net.Socket.connect(Socket.java:633)

19:45:27 [严重]     at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)

19:45:27 [严重]     at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)

19:45:27 [严重]     at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)

19:45:27 [严重]     at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)

19:45:27 [严重]     at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)

19:45:27 [严重]     at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)

19:45:27 [严重]     at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)

19:45:27 [严重]     at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)

19:45:27 [严重]     at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)

19:45:27 [严重]     at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)

19:45:27 [严重]     at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)

19:45:27 [严重]     at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)

19:45:27 [严重]     at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)

19:45:27 [严重]     at com.elikill58.negativity.universal.utils.UniversalUtils.getContentFromURLWithException(UniversalUtils.java:240)

19:45:27 [严重]     at com.elikill58.negativity.universal.utils.UniversalUtils.getContentFromURL(UniversalUtils.java:204)

19:45:27 [严重]     at com.elikill58.negativity.universal.utils.UniversalUtils.getContentFromURL(UniversalUtils.java:192)

19:45:27 [严重]     at com.elikill58.negativity.universal.utils.UniversalUtils.getLatestVersionString(UniversalUtils.java:328)

19:45:27 [严重]     at com.elikill58.negativity.universal.utils.UniversalUtils.getLatestVersion(UniversalUtils.java:332)

19:45:27 [严重]     at com.elikill58.negativity.universal.utils.UniversalUtils.getLatestVersionIfNewer(UniversalUtils.java:341)

19:45:27 [严重]     at com.elikill58.negativity.common.ConnectionManager.lambda$onConnect$3(ConnectionManager.java:88)

19:45:27 [严重]     at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)

19:45:27 [严重]     at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)

19:45:27 [严重]     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)

19:45:27 [严重]     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)

19:45:27 [严重]     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)

19:45:27 [严重]     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)

19:45:27 [严重]     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
==============Log on Paper=================
[19:43:20 INFO]: [Negativity] Enabling Negativity v2.5.1
[19:43:21 INFO]: [Negativity] [Packets-v1_19_R1] Loaded 18 PlayIn, 9 PlayOut, 2 Handshake, 0 Status and 1 negativity-to-platform.
[19:43:21 INFO]: [Negativity] Detected server version: v1_19 (v1_19_R1) using Paper server.
[19:43:21 INFO]: [Negativity] Running with Java 17.0.1
[19:43:21 INFO]: [Negativity] Thanks for buying Negativity <3
[19:43:21 INFO]: [Negativity] Connection to database 127.0.0.1/negativity (with MySQL) done !
[19:43:21 INFO]: [Negativity] Loaded 6 special detections.
[19:43:21 INFO]: [Negativity] Loaded 40 cheat detections.
[19:43:21 INFO]: [Negativity] Migrated 21 files from text files to database one.
[19:43:21 INFO]: [Negativity] Loaded support for GadgetsMenu, ViaVersion, Essentials.
[19:45:08 INFO]: [AuthMe] Lionel90s logged in 118.116.63.74
[19:45:08 WARN]: [Essentials] Permissions lag notice with (LuckPermsHandler). Response took 37.388800ms. Summary: Getting prefix for Lionel90s
[19:45:08 INFO]: [PlaceholderAPI] Successfully registered expansion: tab [2.0.0-pre1]
[19:45:09 INFO]: [Negativity] Proxy companion plugin found, it will be used. 14 plugins founded on proxy.
[19:45:11 INFO]: UUID of player ServerTest is ffd33ff2-bbf6-3810-b07b-bba8353eb3d5
[19:45:11 INFO]: ServerTest[/118.116.63.74:57727] logged in with entity id 2457 at ([world_login]-299.5, 63.9375, 299.5)[19:45:13 INFO]: [Negativity] An error occured while trying to make web request to: https://api.spigotmc.org/legacy/update.php?resource=86874
[19:45:13 WARN]: java.net.SocketTimeoutException: Connect timed out
[19:45:13 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
[19:45:13 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
[19:45:13 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[19:45:13 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
[19:45:13 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
[19:45:13 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[19:45:13 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
[19:45:13 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
[19:45:13 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[19:45:13 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[19:45:13 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
[19:45:13 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[19:45:13 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[19:45:13 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
[19:45:13 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[19:45:13 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[19:45:13 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[19:45:13 WARN]:        at Negativity-2.5.1.jar//com.elikill58.negativity.universal.utils.UniversalUtils.getContentFromURLWithException(UniversalUtils.java:240)
[19:45:13 WARN]:        at Negativity-2.5.1.jar//com.elikill58.negativity.universal.utils.UniversalUtils.getContentFromURL(UniversalUtils.java:204)
[19:45:13 WARN]:        at Negativity-2.5.1.jar//com.elikill58.negativity.universal.utils.UniversalUtils.getContentFromURL(UniversalUtils.java:192)
[19:45:13 WARN]:        at Negativity-2.5.1.jar//com.elikill58.negativity.universal.utils.UniversalUtils.getLatestVersionString(UniversalUtils.java:328)
[19:45:13 WARN]:        at Negativity-2.5.1.jar//com.elikill58.negativity.universal.utils.UniversalUtils.getLatestVersion(UniversalUtils.java:332)
[19:45:13 WARN]:        at Negativity-2.5.1.jar//com.elikill58.negativity.universal.utils.UniversalUtils.getLatestVersionIfNewer(UniversalUtils.java:341)
[19:45:13 WARN]:        at Negativity-2.5.1.jar//com.elikill58.negativity.common.ConnectionManager.lambda$onConnect$3(ConnectionManager.java:88)
[19:45:13 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[19:45:13 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[19:45:13 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[19:45:13 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[19:45:13 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[19:45:13 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[19:45:13 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[19:45:16 INFO]: [Negativity] An error occured while trying to make web request to: https://api.spigotmc.org/legacy/update.php?resource=86874
[19:45:16 WARN]: java.net.SocketTimeoutException: Connect timed out
[19:45:16 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
[19:45:16 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
[19:45:16 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[19:45:16 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
[19:45:16 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
[19:45:16 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[19:45:16 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
[19:45:16 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
[19:45:16 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[19:45:16 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[19:45:16 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
[19:45:16 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[19:45:16 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[19:45:16 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
[19:45:16 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[19:45:16 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[19:45:16 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[19:45:16 WARN]:        at Negativity-2.5.1.jar//com.elikill58.negativity.universal.utils.UniversalUtils.getContentFromURLWithException(UniversalUtils.java:240)
[19:45:16 WARN]:        at Negativity-2.5.1.jar//com.elikill58.negativity.universal.utils.UniversalUtils.getContentFromURL(UniversalUtils.java:204)
[19:45:16 WARN]:        at Negativity-2.5.1.jar//com.elikill58.negativity.universal.utils.UniversalUtils.getContentFromURL(UniversalUtils.java:192)
[19:45:16 WARN]:        at Negativity-2.5.1.jar//com.elikill58.negativity.universal.utils.UniversalUtils.getLatestVersionString(UniversalUtils.java:328)
[19:45:16 WARN]:        at Negativity-2.5.1.jar//com.elikill58.negativity.universal.utils.UniversalUtils.getLatestVersion(UniversalUtils.java:332)
[19:45:16 WARN]:        at Negativity-2.5.1.jar//com.elikill58.negativity.universal.utils.UniversalUtils.getLatestVersionIfNewer(UniversalUtils.java:341)
[19:45:16 WARN]:        at Negativity-2.5.1.jar//com.elikill58.negativity.common.ConnectionManager.lambda$onConnect$3(ConnectionManager.java:88)
[19:45:16 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[19:45:16 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[19:45:16 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[19:45:16 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[19:45:16 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[19:45:16 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[19:45:16 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by Elikill58** [comment]
Hi,

For help about config, it's recommended to come on [discord](https://discord.gg/6r4qYCN). Else, you can find wiki, for example a [list of processor for warns](https://github.com/Elikill58/Negativity/wiki/Warns-%28v2%29#processors). To quickly answer about "which processor use on bungee ?", if you want to use mysql db, set "database".

For the error itself, it seems your server doesn't have access to internet to check if there is update. I will remove this error, and only put warning. To have dev build that remove log, come on discord :)

**Comment by Elikill58** [comment]
Should be fixed since https://github.com/Elikill58/Negativity/commit/a298b527f8b349012952b790d2c5b46368476edb
