### ISSUE TITLE
[Bug] Conflict with carpet

### ISSUE THREAD

**Issue by Dreeam-qwq** [Elikill58/Negativity#347]
### Which platform are you using ?

Other

### Versions of Negativity and of the server

Negativity: latest commit [3ec9d37](https://github.com/Elikill58/Negativity/commit/3ec9d379d84c6a575177256545aed71b82f66a89)
NegativityFabric: latest commit [a73520d](https://github.com/Elikill58/NegativityFabric/commit/a73520d26d07c8edc74d6e71023f5574306084fc)
Server version: 1.18.2 Fabric Loader 0.14.11
Carpet: [1.18.2-1.4.69+v220331](https://github.com/gnembon/fabric-carpet/releases/tag/1.4.69)

### Step to reproduce

1. Add carpet, Negativity and NegativityFabric
2. Launch the server
3. Crash and see the error.

### Errors / Logs

```
[19:35:37] [main/ERROR]: Mixin apply for mod carpet failed carpet.mixins.json:ServerPlayer_scarpetEventMixin from mod carpet -> net.minecraft.class_3222: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_3222::finishedUsingItem with priority 1000 cannot inject into net/minecraft/class_3222::method_6040()V merged by com.elikill58.negativity.fabric.mixin.MixinServerPlayerEntity with priority 1000 [PREINJECT Applicator Phase -> carpet.mixins.json:ServerPlayer_scarpetEventMixin from mod carpet -> Prepare Injections ->  -> redirect$zma000$finishedUsingItem(Lnet/minecraft/class_1657;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_3222::finishedUsingItem with priority 1000 cannot inject into net/minecraft/class_3222::method_6040()V merged by com.elikill58.negativity.fabric.mixin.MixinServerPlayerEntity with priority 1000 [PREINJECT Applicator Phase -> carpet.mixins.json:ServerPlayer_scarpetEventMixin from mod carpet -> Prepare Injections ->  -> redirect$zma000$finishedUsingItem(Lnet/minecraft/class_1657;)V -> Prepare]
        at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) [fabric-loader-0.14.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) [?:?]
        at net.minecraft.class_6396.handler$zna000$fillSystemDetails(class_6396.java:521) [server-intermediary.jar:?]
        at net.minecraft.class_6396.<init>(class_6396.java:57) [server-intermediary.jar:?]
        at net.minecraft.class_128.<init>(class_128.java:32) [server-intermediary.jar:?]
        at net.minecraft.class_128.method_24305(class_128.java:272) [server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:91) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.11.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.11.jar:?]
```
[Pastebin](https://pastebin.com/ACHN9Mui)

**Comment by Dreeam-qwq** [comment]
It seems like the issue of NegativityFabric. [These code](https://github.com/Elikill58/NegativityFabric/blob/58787b79150a360cfccd58911b2004870c6c6317/fabric182/src/com/elikill58/negativity/fabric/mixin/MixinServerPlayerEntity.java#L66) conflict with [this part](https://github.com/gnembon/fabric-carpet/blob/d27767ba981a2f7eb0ca9287df1773e230bae1f5/src/main/java/carpet/mixins/ServerPlayer_scarpetEventMixin.java#L50) of fabric-carpet.
