### ISSUE TITLE
[Bug] Random Error (when starting)

### ISSUE THREAD

**Issue by ImInTheICU** [Elikill58/Negativity#382]
### Which platform are you using ?

Spigot, Paper

### Versions of Negativity and of the server

spigot: v_1_19_R3. Negativity 1.13

### Step to reproduce

Run latest version of Negativity from Spigot-Page

### Errors / Logs

```
[00:02:07 INFO]: [Negativity] ------ Negativity Information ------
[00:02:07 INFO]: [Negativity] This plugin is free, but you can buy the premium version : https://www.spigotmc.org/resources/86874 <3
[00:02:07 INFO]: [Negativity] Founded u/v/w baseBlock's methods
[00:02:07 INFO]: [Negativity] Loaded support for WorldGuard, AdvancedBan, ViaVersion, FloodGate.
[00:02:07 WARN]: java.lang.NoSuchMethodException: net.minecraft.util.MathHelper.a([J)
[00:02:07 WARN]:        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)
[00:02:07 WARN]:        at Negativity-1.13.jar//com.elikill58.negativity.spigot.SpigotNegativity.onEnable(SpigotNegativity.java:322)
[00:02:07 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[00:02:07 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192)
[00:02:07 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[00:02:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[00:02:07 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555)
[00:02:07 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466)
[00:02:07 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[00:02:07 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[00:02:07 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[00:02:07 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
[00:02:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[00:02:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Elikill58** [comment]
Fixed since https://github.com/Elikill58/Negativity/commit/4d6a2f3728537a14a9d4f84467f820200f1f3dce - Need this build:
[Negativity.zip](https://github.com/Elikill58/Negativity/files/11449878/Negativity.zip)
