### ISSUE TITLE
[Bug] obj null warning when player joins or leaves

### ISSUE THREAD

**Issue by Josh65-2201** [Elikill58/Negativity#388]
### Which platform are you using ?

Paper

### Versions of Negativity and of the server

Negativity: 2.6.1
Server: Paper 1.18.2 build 388

### Step to reproduce

1. Join/leave game
2. See console error

### Errors / Logs

```
[23:39:07 WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
[23:39:07 WARN]:        at Negativity-2.6.1.jar//com.elikill58.negativity.api.packets.PacketContent$ContentModifier.<init>(PacketContent.java:133)
[23:39:07 WARN]:        at Negativity-2.6.1.jar//com.elikill58.negativity.api.packets.PacketContent.getSpecificModifier(PacketContent.java:42)
[23:39:07 WARN]:        at Negativity-2.6.1.jar//com.elikill58.negativity.spigot.nms.SpigotVersionAdapter.getChannel(SpigotVersionAdapter.java:158)
[23:39:07 WARN]:        at Negativity-2.6.1.jar//com.elikill58.negativity.spigot.listeners.PacketListeners.getChannel(PacketListeners.java:35)
[23:39:07 WARN]:        at Negativity-2.6.1.jar//com.elikill58.negativity.api.packets.nms.channels.netty.NettyPacketListener.addChannel(NettyPacketListener.java:78)
[23:39:07 WARN]:        at Negativity-2.6.1.jar//com.elikill58.negativity.api.packets.nms.channels.netty.NettyPacketListener.join(NettyPacketListener.java:42)
[23:39:07 WARN]:        at Negativity-2.6.1.jar//com.elikill58.negativity.spigot.listeners.PacketListeners.onPlayerJoin(PacketListeners.java:22)
[23:39:07 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor429.execute(Unknown Source)
[23:39:07 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[23:39:07 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[23:39:07 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[23:39:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669)
[23:39:07 WARN]:        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:363)
[23:39:07 WARN]:        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305)
[23:39:07 WARN]:        at net.minecraft.server.network.PlayerConnection.c(PlayerConnection.java:305)
[23:39:07 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:567)
[23:39:07 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:231)
[23:39:07 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1623)
[23:39:07 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:483)
[23:39:07 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1456)
[23:39:07 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[23:39:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[23:39:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[23:39:07 WARN]: java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.pipeline()" because "channel" is null
[23:39:07 WARN]:        at Negativity-2.6.1.jar//com.elikill58.negativity.api.packets.nms.channels.netty.NettyPacketListener.addChannel(NettyPacketListener.java:83)
[23:39:07 WARN]:        at Negativity-2.6.1.jar//com.elikill58.negativity.api.packets.nms.channels.netty.NettyPacketListener.join(NettyPacketListener.java:42)
[23:39:07 WARN]:        at Negativity-2.6.1.jar//com.elikill58.negativity.spigot.listeners.PacketListeners.onPlayerJoin(PacketListeners.java:22)
[23:39:07 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor429.execute(Unknown Source)
[23:39:07 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[23:39:07 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[23:39:07 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[23:39:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669)
[23:39:07 WARN]:        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:363)
[23:39:07 WARN]:        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305)
[23:39:07 WARN]:        at net.minecraft.server.network.PlayerConnection.c(PlayerConnection.java:305)
[23:39:07 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:567)
[23:39:07 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:231)
[23:39:07 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1623)
[23:39:07 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:483)
[23:39:07 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1456)
[23:39:07 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[23:39:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[23:39:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Josh65-2201** [comment]
Yes I just got the dev build one today at 19:35 from dev build v2 channel on discord

**Comment by Elikill58** [comment]
Fixed since few build
