### ISSUE TITLE
[Bug] Unable to start on Spigot 1.20.2

### ISSUE THREAD

**Issue by Gasterbuzzer** [Elikill58/Negativity#417]
### Which platform are you using ?

Spigot

### Versions of Negativity and of the server

Negativity v2.7
Server is running CraftBukkit version 3926-Spigot-dba3cdc-ffb1319 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT)

### Step to reproduce

1. Inserting into Plugins folder on fresh install of Spigot

### Errors / Logs

[09:37:38] [Server thread/INFO]: [Negativity] Enabling Negativity v2.7
[09:37:38] [Server thread/WARN]: java.lang.NoSuchFieldException: ping
[09:37:38] [Server thread/WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2782)
[09:37:38] [Server thread/WARN]:        at com.elikill58.negativity.spigot.nms.SpigotVersionAdapter.<init>(SpigotVersionAdapter.java:59)
[09:37:38] [Server thread/WARN]:        at com.elikill58.negativity.spigot.nms.Spigot_UnknowVersion.<init>(Spigot_UnknowVersion.java:15)
[09:37:38] [Server thread/WARN]:        at com.elikill58.negativity.spigot.nms.SpigotVersionAdapter.getVersionAdapter(SpigotVersionAdapter.java:310)
[09:37:38] [Server thread/WARN]:        at com.elikill58.negativity.spigot.SpigotNegativity.onEnable(SpigotNegativity.java:68)
[09:37:38] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[09:37:38] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[09:37:38] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[09:37:38] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:548)
[09:37:38] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:462)
[09:37:38] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:577)
[09:37:38] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:400)
[09:37:38] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[09:37:38] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954)
[09:37:38] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298)
[09:37:38] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[09:37:38] [Server thread/WARN]: [Negativity] Failed to find version adapter for v1_20_R2.
[09:37:38] [Server thread/WARN]: [Negativity] Unknow server version v1_20_R2 ! Some problems can appears.
[09:37:38] [Server thread/INFO]: [Negativity] Running with Java 21.0.1
[09:37:38] [Server thread/INFO]: [Negativity] Thanks for buying Negativity <3
[09:37:38] [Server thread/ERROR]: Error occurred while enabling Negativity v2.7 (Is it up to date?)
java.util.ServiceConfigurationError: com.elikill58.negativity.universal.detections.Special: Provider com.elikill58.negativity.common.special.WorldDownloader could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:586) ~[?:?]
        at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813) ~[?:?]
        at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729) ~[?:?]
        at java.util.ServiceLoader$3.next(ServiceLoader.java:1403) ~[?:?]
        at com.elikill58.negativity.universal.detections.Special.loadSpecial(Special.java:76) ~[?:?]
        at com.elikill58.negativity.universal.Negativity.loadNegativity(Negativity.java:308) ~[?:?]
        at com.elikill58.negativity.spigot.SpigotNegativity.onEnable(SpigotNegativity.java:76) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:548) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3926-Spigot-dba3cdc-ffb1319]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:462) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3926-Spigot-dba3cdc-ffb1319]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:577) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3926-Spigot-dba3cdc-ffb1319]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:400) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3926-Spigot-dba3cdc-ffb1319]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3926-Spigot-dba3cdc-ffb1319]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3926-Spigot-dba3cdc-ffb1319]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3926-Spigot-dba3cdc-ffb1319]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use WDL|INIT)
        at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:503) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.registerIncomingPluginChannel(StandardMessenger.java:216) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at com.elikill58.negativity.spigot.SpigotAdapter.registerNewIncomingChannel(SpigotAdapter.java:266) ~[?:?]
        at com.elikill58.negativity.common.special.WorldDownloader.<init>(WorldDownloader.java:21) ~[?:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789) ~[?:?]
        ... 16 more

**Comment by Gasterbuzzer** [comment]
Perhaps a helping point, the free version seems to be working normally without any issues.

**Comment by Elikill58** [comment]
Can you come on discord, and give me your spigotmc name ? A dev build fix it

**Comment by Elikill58** [comment]
Fixed with #416
