### ISSUE TITLE
[Bug] Error when opening a chest under Folia

### ISSUE THREAD

**Issue by lRENyaaa** [Elikill58/Negativity#424]
### Which platform are you using ?

Spigot

### Versions of Negativity and of the server

Negativity 2.7.2-SNAPSHOT, Folia v1_20_R3

### Step to reproduce

Using Folia, and open the chest   
For sure, it's line 24 in ActualizeInvTimer.java that causes the problem, p.getOpenInventory() should be executed in EntityScheduler, but I don't know how to fix it

### Errors / Logs

Thread Region Scheduler Thread #0 failed main thread check: Cannot read world asynchronously
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:57) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlock.getNMS(CraftBlock.java:80) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlockStates.getBlockState(CraftBlockStates.java:242) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlock.getState(CraftBlock.java:349) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at net.minecraft.world.level.block.entity.BlockEntity.getOwner(BlockEntity.java:259) ~[?:?]
        at net.minecraft.world.level.block.entity.BlockEntity.getOwner(BlockEntity.java:252) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.inventory.CraftInventory.getHolder(CraftInventory.java:555) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at com.elikill58.negativity.spigot.impl.inventory.SpigotInventory.<init>(SpigotInventory.java:24) ~[Negativity-2.7.2-SNAPSHOT.jar:?]
        at com.elikill58.negativity.spigot.impl.entity.SpigotPlayer.getOpenInventory(SpigotPlayer.java:337) ~[Negativity-2.7.2-SNAPSHOT.jar:?]
        at com.elikill58.negativity.common.timers.ActualizeInvTimer.run(ActualizeInvTimer.java:24) ~[Negativity-2.7.2-SNAPSHOT.jar:?]
        at com.elikill58.negativity.spigot.scheduler.FoliaScheduler.lambda$runRepeating$3(FoliaScheduler.java:64) ~[Negativity-2.7.2-SNAPSHOT.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[luminol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[luminol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:294) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Elikill58** [comment]
I fixed almost all issues with Folia with new versions, and this one seems to be fixed by Folia's dev. I'm closing this issue
