### ISSUE TITLE
spams console with errors on 1.14.2

### ISSUE THREAD

**Issue by ghost** [Elikill58/Negativity#6]
[17:40:29] [Server thread/WARN]: [Negativity] Task #5 for Negativity v1.2.2 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.elikill58.negativity.spigot.SpigotNegativityPlayer$FlyingReason
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.<init>(SpigotNegativityPlayer.java:75) ~[?:?]
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.getNegativityPlayer(SpigotNegativityPlayer.java:578) ~[?:?]
        at com.elikill58.negativity.spigot.timers.TimerAnalyzePacket.run(TimerAnalyzePacket.java:25) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[17:40:29] [Craft Scheduler Thread - 0/WARN]: [Negativity] Plugin Negativity v1.2.2 generated an exception while executing task 4
java.lang.NoClassDefFoundError: Could not initialize class com.elikill58.negativity.spigot.SpigotNegativityPlayer$FlyingReason
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.<init>(SpigotNegativityPlayer.java:75) ~[?:?]
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.getNegativityPlayer(SpigotNegativityPlayer.java:578) ~[?:?]
        at com.elikill58.negativity.spigot.timers.ActualizeInvTimer.run(ActualizeInvTimer.java:34) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[17:40:29] [Craft Scheduler Thread - 0/WARN]: [Negativity] Plugin Negativity v1.2.2 generated an exception while executing task 4
java.lang.NoClassDefFoundError: Could not initialize class com.elikill58.negativity.spigot.SpigotNegativityPlayer$FlyingReason
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.<init>(SpigotNegativityPlayer.java:75) ~[?:?]
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.getNegativityPlayer(SpigotNegativityPlayer.java:578) ~[?:?]
        at com.elikill58.negativity.spigot.timers.ActualizeInvTimer.run(ActualizeInvTimer.java:34) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[17:40:30] [Craft Scheduler Thread - 0/WARN]: [Negativity] Plugin Negativity v1.2.2 generated an exception while executing task 4
java.lang.NoClassDefFoundError: Could not initialize class com.elikill58.negativity.spigot.SpigotNegativityPlayer$FlyingReason
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.<init>(SpigotNegativityPlayer.java:75) ~[?:?]
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.getNegativityPlayer(SpigotNegativityPlayer.java:578) ~[?:?]
        at com.elikill58.negativity.spigot.timers.ActualizeInvTimer.run(ActualizeInvTimer.java:34) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[17:40:30] [Server thread/WARN]: [Negativity] Task #3 for Negativity v1.2.2 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.elikill58.negativity.spigot.SpigotNegativityPlayer$FlyingReason
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.<init>(SpigotNegativityPlayer.java:75) ~[?:?]
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.getNegativityPlayer(SpigotNegativityPlayer.java:578) ~[?:?]
        at com.elikill58.negativity.spigot.timers.ActualizeClickTimer.run(ActualizeClickTimer.java:14) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[17:40:30] [Server thread/WARN]: [Negativity] Task #5 for Negativity v1.2.2 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.elikill58.negativity.spigot.SpigotNegativityPlayer$FlyingReason
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.<init>(SpigotNegativityPlayer.java:75) ~[?:?]
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.getNegativityPlayer(SpigotNegativityPlayer.java:578) ~[?:?]
        at com.elikill58.negativity.spigot.timers.TimerAnalyzePacket.run(TimerAnalyzePacket.java:25) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[17:40:30] [Craft Scheduler Thread - 0/WARN]: [Negativity] Plugin Negativity v1.2.2 generated an exception while executing task 4
java.lang.NoClassDefFoundError: Could not initialize class com.elikill58.negativity.spigot.SpigotNegativityPlayer$FlyingReason
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.<init>(SpigotNegativityPlayer.java:75) ~[?:?]
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.getNegativityPlayer(SpigotNegativityPlayer.java:578) ~[?:?]
        at com.elikill58.negativity.spigot.timers.ActualizeInvTimer.run(ActualizeInvTimer.java:34) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[17:40:30] [Craft Scheduler Thread - 0/WARN]: [Negativity] Plugin Negativity v1.2.2 generated an exception while executing task 4
java.lang.NoClassDefFoundError: Could not initialize class com.elikill58.negativity.spigot.SpigotNegativityPlayer$FlyingReason
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.<init>(SpigotNegativityPlayer.java:75) ~[?:?]
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.getNegativityPlayer(SpigotNegativityPlayer.java:578) ~[?:?]
        at com.elikill58.negativity.spigot.timers.ActualizeInvTimer.run(ActualizeInvTimer.java:34) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[17:40:30] [Craft Scheduler Thread - 0/WARN]: [Negativity] Plugin Negativity v1.2.2 generated an exception while executing task 4
java.lang.NoClassDefFoundError: Could not initialize class com.elikill58.negativity.spigot.SpigotNegativityPlayer$FlyingReason
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.<init>(SpigotNegativityPlayer.java:75) ~[?:?]
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.getNegativityPlayer(SpigotNegativityPlayer.java:578) ~[?:?]
        at com.elikill58.negativity.spigot.timers.ActualizeInvTimer.run(ActualizeInvTimer.java:34) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[17:40:31] [Craft Scheduler Thread - 0/WARN]: [Negativity] Plugin Negativity v1.2.2 generated an exception while executing task 4
java.lang.NoClassDefFoundError: Could not initialize class com.elikill58.negativity.spigot.SpigotNegativityPlayer$FlyingReason
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.<init>(SpigotNegativityPlayer.java:75) ~[?:?]
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.getNegativityPlayer(SpigotNegativityPlayer.java:578) ~[?:?]
        at com.elikill58.negativity.spigot.timers.ActualizeInvTimer.run(ActualizeInvTimer.java:34) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[17:40:31] [Server thread/WARN]: [Negativity] Task #3 for Negativity v1.2.2 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.elikill58.negativity.spigot.SpigotNegativityPlayer$FlyingReason
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.<init>(SpigotNegativityPlayer.java:75) ~[?:?]
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.getNegativityPlayer(SpigotNegativityPlayer.java:578) ~[?:?]
        at com.elikill58.negativity.spigot.timers.ActualizeClickTimer.run(ActualizeClickTimer.java:14) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[17:40:31] [Craft Scheduler Thread - 0/WARN]: [Negativity] Plugin Negativity v1.2.2 generated an exception while executing task 4
java.lang.NoClassDefFoundError: Could not initialize class com.elikill58.negativity.spigot.SpigotNegativityPlayer$FlyingReason
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.<init>(SpigotNegativityPlayer.java:75) ~[?:?]
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.getNegativityPlayer(SpigotNegativityPlayer.java:578) ~[?:?]
        at com.elikill58.negativity.spigot.timers.ActualizeInvTimer.run(ActualizeInvTimer.java:34) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[17:40:31] [Server thread/WARN]: [Negativity] Task #5 for Negativity v1.2.2 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.elikill58.negativity.spigot.SpigotNegativityPlayer$FlyingReason
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.<init>(SpigotNegativityPlayer.java:75) ~[?:?]
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.getNegativityPlayer(SpigotNegativityPlayer.java:578) ~[?:?]
        at com.elikill58.negativity.spigot.timers.TimerAnalyzePacket.run(TimerAnalyzePacket.java:25) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[17:40:31] [Craft Scheduler Thread - 0/WARN]: [Negativity] Plugin Negativity v1.2.2 generated an exception while executing task 4
java.lang.NoClassDefFoundError: Could not initialize class com.elikill58.negativity.spigot.SpigotNegativityPlayer$FlyingReason
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.<init>(SpigotNegativityPlayer.java:75) ~[?:?]
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.getNegativityPlayer(SpigotNegativityPlayer.java:578) ~[?:?]
        at com.elikill58.negativity.spigot.timers.ActualizeInvTimer.run(ActualizeInvTimer.java:34) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[17:40:31] [Craft Scheduler Thread - 0/WARN]: [Negativity] Plugin Negativity v1.2.2 generated an exception while executing task 4
java.lang.NoClassDefFoundError: Could not initialize class com.elikill58.negativity.spigot.SpigotNegativityPlayer$FlyingReason
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.<init>(SpigotNegativityPlayer.java:75) ~[?:?]
        at com.elikill58.negativity.spigot.SpigotNegativityPlayer.getNegativityPlayer(SpigotNegativityPlayer.java:578) ~[?:?]
        at com.elikill58.negativity.spigot.timers.ActualizeInvTimer.run(ActualizeInvTimer.java:34) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Comment by Elikill58** [comment]
Hello,

Sorry, i didn't receive any notification about your issue.
Your error is very strange. It appear only when you change the plugin jar when the server is running. Try to stop your server, re download the spigot version and finally start your server.

**Comment by Elikill58** [comment]
Again forget to write this issue in commit message but it's fixed !
